### ISSUE TITLE
Tampilannya tidak terbaca,

### ISSUE THREAD

**Issue by murifai** [dikiwidia/tokoku#9]
di saya ko tampilannya tidak terbaca ya? apakah ada solusi?
![image](https://user-images.githubusercontent.com/38082775/111588174-c4988800-87f5-11eb-8786-5c29d9de825e.png)

**Comment by dikiwidia** [comment]
![image](https://user-images.githubusercontent.com/8361706/111592949-04fb0480-87fc-11eb-93b3-4291c9a5652e.png)
Untuk tampilannya sudah sangat jelas. Repositorinya masih bekerja dengan baik. Usahakan untuk membaca [ReadMe](https://github.com/dikiwidia/tokoku/blob/master/README.md) terlebih dahulu. Dan ikuti langkah instalasinya. 

Untuk lebih jelas terkait instalasi dan kebutuhan server yang digunakan guna memasang aplikasi ini, saya menyarankan Anda mempelajarinya di situs resmi [Laravel](https://laravel.com/docs/5.2/#server-requirements) 

Terima kasih
